apiVersion: v1
kind: Service
metadata:
  name: angular-demo-backend
  labels:
    group: experiment
spec:
  selector: #control what pods to expose to the cluster/outside
    app: angular-demo
    tier: backend
  ports:
    - protocol: 'TCP'
      port: 80
      targetPort: 80
      
  type: LoadBalancer

--- # Seperator between the two objects
apiVersion: apps/v1
kind: Deployment # Could alternativley define a service or a job!

metadata:
  name: angular-demo-deployment
  labels:
    group: experiment

spec: # definition of our deployment
  replicas: 1 # how many pods do you want
  selector:
    matchLabels:
      app: angular-demo
      tier: backend

  template: # definition of our pods
    metadata:
      labels:
        app: angular-demo
        tier: backend

    spec:
      containers:
        - name: angular-site
          image: ridhachowdhury/angular-demo:latest