apiVersion: v1
kind: Service
metadata:
  name: second-app-backend
  labels:
    group: example
spec:
  selector: #control what pods to expose to the cluster/outside
    app: second-app
    tier: backend
  ports:
    - protocol: 'TCP'
      port: 80
      targetPort: 8080
      
  type: LoadBalancer

--- # Seperator between the two objects
apiVersion: apps/v1
kind: Deployment # Could alternativley define a service or a job!

metadata:
  name: second-app-deployment
  labels:
    group: example

spec: # definition of our deployment
  replicas: 1 # how many pods do you want
  selector:
    matchLabels:
      app: second-app
      tier: backend

  template: # definition of our pods
    metadata:
      labels:
        app: second-app
        tier: backend

    spec:
      containers:
        - name: second-node
          image: ridhachowdhury/kub-first-app:3
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            periodSecond: 10
            initialDelaySeconds: 5
          
        # - name: second-node
        #   image: ridhachowdhury/first-app