apiVersion: v1
kind: Service
metadata:
  name: second-app-backend
spec:
  selector: #control what pods to expose to the cluster/outside
    app: second-app
    tier: backend
  ports:
    - protocol: 'TCP'
      port: 80
      targetPort: 8080
      
  type: LoadBalancer
    